### ISSUE TITLE
I think you can apply with https://utopian.io and get paid in steem

### ISSUE THREAD

**Issue by nurazhar** [vicky002/AlgoWiki#100]
Utopian Rewards Open Source Contributors!
Create a Contributor Report to share the latest contributions you made to an Open Source project. The Utopian community will vote and get you rewarded $

**Comment by vicky002** [comment]
Hey @nurazhar , I didn't know about it, Thank you!

I will submit a Contributor Report on Utopian very soon.

Feel free to close this issue.
