### ISSUE TITLE
Description update

### ISSUE THREAD

**Issue by michaelmior** [vicky002/AlgoWiki#102]
> Repository which contains all the links and resources on different topics of Computer Science

AlgoWiki looks great! But I couldn't help but notice the description above. "all" is obviously not true and even if it were possible to collect all links and resources, that would not be very helpful since most would be fairly low quality. I'd suggest removing the "all."

**Comment by vicky002** [comment]
@michaelmior , agree with you. Will remove `all` very soon.

**Comment by vicky002** [comment]
Fixed. #102
