### ISSUE TITLE
Use AlgoWiki for MIT conference?

### ISSUE THREAD

**Issue by dazzaji** [vicky002/AlgoWiki#14]
As part of a legal technologies conference at MIT next month, I would like to use the AlgoWiki for workshop participants to add information about law, regulatory and policy related to algorithms.
- Context: We have a nice group coming together for the "Open Algorithms" track, including law professors, law students, lawyers joined by some talented computer scientists, developers and civic hackers who will be focused on learning and rapid prototyping some projects.   
- The Need: I'd like to provide them an easy way to add their knowledge and to learn more about algorithms (but I don't want to build it!).  Most/all of the are familiar with using markdown and a Wiki seems the right format for this type of collection/sharing of info.  I'm asking if it's ok because I predict whatever system used will quickly become messy or perhaps even chaotic for a while, until they fall into a good pattern.  My hope is that the predicted emergence of raw chaos will last only until one or two members of the group can't stand it anymore and steps forward to start curating. Based on past performance, it is foreseeable I will not personally do any curation of anything for very long, but I do want to give these nice "eager to learn" people a place to discover, share and build up a body of knowledge.  
## Couple Ways We Could Use AlgoWiki
- Option 1:  I could set it up so the group knows MIT/law is only forking the repo, not the project, and the idea is to add/curate a little and make a pull request, then add/curate a little more and make a pull request, so that when you or anybody else in the world adds more knowledge to the Wiki everybody can benefit.  The cost for me that getting lawyers to commit work early and often can be akin to attempting field dentistry on an unrestrained sabertooth and the cost for you is that the pull requests would need to merged or answered on a timely basis or momentum/motivation will soon be lost.
- Options 2: I could fork the overall project into one of the repositories used for law.MIT.edu projects or a workshop member's repo.  However, this would keep the knowledge isolated and seems a needless duplication of at perhaps leaves the world with a confusing choice of which of the active systems containing significantly amounts of identical information they should make contributions to in the future. The cost of this option from my perspective is cutting the anchor to your project and the existing clear, functional focus on algorithm technology resources risks a drift by the lawyers into increasingly murky categories of questionable technical merit and a descent into the mumbo-jumbo of legalese.

**Comment by vicky002** [comment]
Hi @dazzaji Sir, 

Thanks for reaching out. I'm glad you chose AlgoWiki for the workshop. 

Options 1 Seems perfectly fine. I'd love to answer queries, merge pull requests. I'm quite active here so I'll be quick in answering queries and accepting pull requests. It'll help us both. 

Let me know if I can do something more! 

Thank you :)

**Comment by vicky002** [comment]
Hello @dazzaji sir,  any update on this? Should I close this issue?
