### ISSUE TITLE
Links in main README are hard links to the original repo and branch

### ISSUE THREAD

**Issue by havanagrawal** [vicky002/AlgoWiki#162]
Links to each topic have the username "vicky002" and the branch "gh-pages" hardcoded in the URL path, which makes forks and branches behave strangely, and makes them dependent on the original repo/branch respectively.

**Suggestion**

Update all links to be relative paths to the repo resource. For example:

```
* [All about C](https://github.com/vicky002/AlgoWiki/blob/gh-pages/C/sources.md)
```

should be

```
* [All about C](C/sources.md)
```

**Reference**: https://github.com/blog/1395-relative-links-in-markup-files

**Comment by vicky002** [comment]
I agree. This was in my list since a very long time, got involved myself in lot of things so hard to manage. 

Thanks for pointing this out.

**Comment by vicky002** [comment]
If no one is taking this in the next 24 hours, I'll assign it to myself. 👍

**Comment by ReneVolution** [comment]
Lets so it :)

**Comment by ReneVolution** [comment]
Oh .. someone was faster ...

**Comment by vicky002** [comment]
@ReneVolution Yes! 😄 

This is done, closing it now.
