### ISSUE TITLE
We are looking for maintainers

### ISSUE THREAD

**Issue by vicky002** [vicky002/AlgoWiki#190]
Hello Contributors!

I'm looking for maintainers for AlgoWiki and couple of my own OSS projects, need someone who can spend an hour daily working on the PR, verifying commit messages and commenting on issues. I also need someone who can work with me on building the website for AlgoWiki. 

## If you want to be a maintainer, please write to me at - hello@eulercoder.com
With following details 

- A small intro about yourself
- Why do you want to be a part of AlgoWiki?
- How many hours can you give daily?
- Add your Github and LinkedIn profile links. 

That's all. 
Maintainers will be announced in this thread, in about 10 days.

**Comment by Byte7** [comment]
Closing this issue.

**Comment by Byte7** [comment]
Closing the issue.
