### ISSUE TITLE
Add resources to Bash scripting

### ISSUE THREAD

**Issue by Byte7** [vicky002/AlgoWiki#227]

**Comment by Yash-Handa** [comment]
Hi @Byte7 
I would love to add the resources related to **Bash Scripting** in AlgoWiki/Bash_Scripting/resources.md if no one else is working on this issue.
Please Let me know ASAP.

**Comment by shreyateeza** [comment]
@Byte7 PR  #232 created ! :+1:

**Comment by Byte7** [comment]
@Yash-Handa You can go forward and add the resources. Also, you can add to any other topic you like. Sorry for delayed reply, kinda busy!😅

**Comment by sagar-barapatre** [comment]
Is this issue still open??
I can add more if you want.
