### ISSUE TITLE
Video files in repo?

### ISSUE THREAD

**Issue by TimothyBramlett** [vicky002/AlgoWiki#28]
I noticed we have several hundred megabytes of video files currently in the repo in the Linux folder.  Do you think we should get those hosted somewhere else and maybe just link to them?

**Comment by vicky002** [comment]
Hi @TimothyBramlett, 

If you have all those video files in your repo then no need to host it anywhere. Create a file in a suitable section and just link to them. 👍

**Comment by TimothyBramlett** [comment]
True, but the only problem with that is then you have a several hundred gigabyte repo that new contributors have to pull! :)

**Comment by vicky002** [comment]
I am guessing, you are talking about your repo which has videos files, not in **AlgoWiki** repo. If this is the case just then add the links of those videos in AlgoWiki.  

No video files should be there in AlgoWiki. Yes, there are few in `Linux` folder and I am going to host it somewhere very soon.

**Comment by TimothyBramlett** [comment]
Oh, ok yeah I meant the ones in the Linux Folder.

Sounds good! 👍

**Comment by vicky002** [comment]
Feel free to contribute to AlgoWIki and help us in collecting and curating all the CS resources at one place 👍 
I'm closing this issue for now :) 

Thanks!

**Comment by TimothyBramlett** [comment]
Thanks!  I will do so! :)
