### ISSUE TITLE
Add some html css resources

### ISSUE THREAD

**Issue by siva-krish45** [vicky002/AlgoWiki#356]
it would be good if u give some websites rather than book pdfs

**Comment by priyang12** [comment]
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">UI Graphics</h2><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; border-left: 0.25em solid var(--color-markdown-blockquote-border); color: var(--color-text-tertiary); padding: 0px 1em; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Websites and resources with modern UI components in different formats such as PSD, Sketch, Figma, etc. They are great for ideas for web components/UI</p></blockquote>

Website | Description
-- | --
UI Design Daily | Awesome UI Components of all types
100 Daily UI | Free Figma library of products, elements, and screens
Sketch App Sources | Sketch UIs, wireframes, icons and much more
Humaaans | Cool illustrations of people with the ability to mix and match
Paaatterns | Free collection of beautiful patterns for all vector formats
thepatternlibrary | Free beautiful background patterns
404 illustration | Free illustrations for 404 pages


</body>
</html>
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Colors</h2><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; border-left: 0.25em solid var(--color-markdown-blockquote-border); color: var(--color-text-tertiary); padding: 0px 1em; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Websites and resources that help with choices related to colors</p></blockquote>

Website | Description
-- | --
Color Brewer 2 | The original color palette generator, also supporting color blindness. Probably the scientifically best option. Also probably not the prettiest.
Colormind.io | Color palette generator
ColorCurves.app | Color palette generator that uses curves to generate color palettes


</body>
</html>
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Stock Photos</h2><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; border-left: 0.25em solid var(--color-markdown-blockquote-border); color: var(--color-text-tertiary); padding: 0px 1em; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Websites that offer free stock photos of all kinds for your websites and apps</p></blockquote>

Website | Description
-- | --
Pexels | Free stock photos shared by talented creators
Unsplash | The internet’s source of freely usable images
Pixabay | Over 1.7 million+ high-quality stock images and videos
Magdeleine | Gallery & free high-resolution photo everyday
Picspree | Royalty free images, stock photos, illustrations, and vectors


</body>
</html>
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Vectors &amp; Clip Art</h2><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; border-left: 0.25em solid var(--color-markdown-blockquote-border); color: var(--color-text-tertiary); padding: 0px 1em; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Free vectors, clipart, illustrations, patterns and more</p></blockquote>

Website | Description
-- | --
Vecteezy | Find and download free vector art
Freepik | Free vectors, stock photos, PSD and icons
Free Vectors | Community of vector lovers who share free vector graphics
PNGTree | png, backgrounds, templates, text effects
Vector4Free | Free vector graphics


</body>
</html>

**Comment by gursparsh** [comment]
Can I start working on this issue?

**Comment by Stark-developer01** [comment]
I can add productive resources, should I add?

**Comment by av-feaster** [comment]
I can contribute to it!

**Comment by BellatrixLestrangee** [comment]
Hi @siva-krish45 , 
Can I be assigned this issue? 
Thanks

**Comment by vicky002** [comment]
Hey Guys @gursparsh @Stark-developer01 @av-feaster @BellatrixLestrangee — Sure, please go ahead and contribute as much as you can.

Raise separate PRs and make sure to squash all your commits into one. It should one only one commit, no multiple commits allowed. 

Thank you! 😊

**Comment by Byte7** [comment]
Closing this issue.
