### ISSUE TITLE
I have the absolute best collection of resources on operating systems

### ISSUE THREAD

**Issue by Francesco601** [vicky002/AlgoWiki#448]
<a href="https://github.com/Francesco601/BEST-Operating-System-Resources"> BEST OS Resources </a>

**Comment by vicky002** [comment]
This is really good @Francesco601! It would be nice to get this added in AlgoWiki Repo. 

Yes please go ahead and add the resources. Please make sure resources are well organized. I will make sure to mention this OS resources are contributed by you ❤️ Thank you!
