### ISSUE TITLE
I have best collection of DBMS resources 

### ISSUE THREAD

**Issue by Gawade15** [vicky002/AlgoWiki#522]
As I am a newbie in open source, I want to start my contribution. After going through your repository, I noticed there aren't any DBMS resources. Can I add a 'DBMS Resources' folder to your repository?

**Comment by vicky002** [comment]
Yes please go ahead and add the resources. Please make sure resources are completely free and does not require any trial or entering card to access. Promotional links of Scala or Unacademy will not be accepted.
